language: ruby
rvm:
  - 1.9.3
#  - 1.8.7
#  - 1.9.2

#Prevents installation of plugin's gemfile
gemfile: non-existent-gemfile

before_install:
  ## Set one of these:
  # Tarball with specific branch or tag (preferred)
  - export MAIN_ARCHIVE="https://github.com/chiliproject/chiliproject/archive/v3.3.0.tar.gz"
  # Git repo of the ChiliProject/Redmine for testing against master
  - export MAIN_REPO="git://github.com/chiliproject/chiliproject.git"

  # Name of your plugin's repo
  - export REPO_NAME=chiliproject_private_issues
  # Plugin's name/directory
  - export PLUGIN_NAME=$REPO_NAME
  - export TARGET_DIR="$HOME/chiliproject"
before_script: "./test/ci/before_script.sh"
script: "./test/ci/script.sh"

env:
  - "DB=mysql2 BUNDLE_WITHOUT=rmagick:mysql:postgres:sqlite"
  - "DB=postgres BUNDLE_WITHOUT=rmagick:mysql:mysql2:sqlite"
